/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    '[...all]': typeof import('./../components/[...all].vue')['default']
    Chart: typeof import('./../components/core/Chart/index.vue')['default']
    ElTree: typeof import('element-plus/es')['ElTree']
    NavBar: typeof import('./../components/base/NavBar/index.vue')['default']
    Popup: typeof import('./../components/core/Popup/index.vue')['default']
    RefreshList: typeof import('./../components/core/RefreshList/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./../components/base/Search/index.vue')['default']
    StepsCard: typeof import('./../components/base/StepsCard/index.vue')['default']
    Tab: typeof import('./../components/base/Tab/index.vue')['default']
    TabBar: typeof import('./../components/base/TabBar/index.vue')['default']
    TableTree: typeof import('./../components/core/TableTree/index.vue')['default']
    Upload: typeof import('./../components/core/Upload/index.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanIcon: typeof import('vant/es')['Icon']
    VanList: typeof import('vant/es')['List']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    Waterfull: typeof import('./../components/core/Waterfull/index.vue')['default']
  }
}
