/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    '[...all]': typeof import('./../components/[...all].vue')['default']
    Chart: typeof import('./../components/core/Chart/index.vue')['default']
    GhostButton: typeof import('./../components/GhostButton/index.vue')['default']
    NavBar: typeof import('./../components/base/NavBar/index.vue')['default']
    Organization: typeof import('./../components/business/Organization/index.vue')['default']
    Popup: typeof import('./../components/core/Popup/index.vue')['default']
    RefreshList: typeof import('./../components/core/RefreshList/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./../components/base/Search/index.vue')['default']
    TabBar: typeof import('./../components/base/TabBar/index.vue')['default']
    Upload: typeof import('./../components/core/Upload/index.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanIcon: typeof import('vant/es')['Icon']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    Waterfull: typeof import('./../components/core/Waterfull/index.vue')['default']
  }
}
